# Generated by Django 5.0 on 2023-12-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
